### ISSUE TITLE
Add 'Word wrap' feature

### ISSUE THREAD

**Issue by Mholsen** [bhavesh-jadav/Advance-Card#20]
Hi! Thanks for your great work!
Can you add the 'Word wrap' feature that is already on the standard Microsoft card?
In combination with the Advance-Card's ability to change alignment, this will make it close to perfect for displaying text in a card format!
Cheers!

**Comment by MikeTechSpeak** [comment]
As an extension of this, a means to force a wrap. IE allow it to render a carriage return linefeed, UNICHAR(10), etc into a visible line break.

**Comment by bhavesh-jadav** [comment]
This feature will be available in next version

**Comment by DanielLeach10** [comment]
Hi, has the next version been released yet? Thanks!

**Comment by MikeTechSpeak** [comment]
Do you have a time frame on the next release? This feature has been added for almost a year but it hasn't been pushed to the next version yet.

**Comment by bhavesh-jadav** [comment]
I have published the new version and it is under review by Power BI and AppSource Team. This is 3rd  time I have submitted and previous submissions were rejected due to minor, unrelated things to visual. Lets hope it gets accepted this time.

**Comment by shjacobs303** [comment]
Has it been accepted yet?

**Comment by mrssprecious** [comment]
Hi, was there an update to this? I'm on 2.1.1 but still can't find how to word wrap?

**Comment by palaris-chris** [comment]
@bhavesh-jadav I'm also on 2.1.1 and doesn't appear to have word-wrap functionality. Would be an amazing feature if development ever gets resumed on this project. It is otherwise superior to the standard "Card" visual in every way.
