### ISSUE TITLE
Vertical Alignment of Text on Power BI mobile app - iOS different from desktop / web

### ISSUE THREAD

**Issue by scrampy** [bhavesh-jadav/Advance-Card#27]
Vertical alignment of the data label when rendered on Power BI App on iOS does not match what is seen in Power BI Desktop or in browser on app.powerbi.com.  This leads to unpredictable results.

**To Reproduce**
See attached screenshots and pbix file, renamed to .zip, but not zipped.

**Expected behavior**
Alignment of text on iOS should match what is seen on other platforms.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.110

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 12
 - Browser Power BI Mobile App
 - Version 17.0
![img_0234](https://user-images.githubusercontent.com/3229013/49692601-8a2ae580-fb2c-11e8-8da6-a56ddba392b0.PNG)
![img_0235](https://user-images.githubusercontent.com/3229013/49692603-8c8d3f80-fb2c-11e8-85e6-a9a50d3a22af.PNG)
![2018-12-08_20h42_16](https://user-images.githubusercontent.com/3229013/49692604-9020c680-fb2c-11e8-99db-9bbd2997642f.png)
![2018-12-08_20h41_38](https://user-images.githubusercontent.com/3229013/49692605-93b44d80-fb2c-11e8-93ce-6536e0f39b54.png)
![2018-12-08_20h40_54](https://user-images.githubusercontent.com/3229013/49692606-9747d480-fb2c-11e8-8d2a-d1c4560ba298.png)
[Advance Card iOS Issue.zip](https://github.com/bhavesh-jadav/Advance-Card/files/2660182/Advance.Card.iOS.Issue.zip)

**Comment by bhavesh-jadav** [comment]
Hi @scrampy 

Can you please check with v2.0.4 and see if this issue exists?

**Comment by scrampy** [comment]
Hi @bhavesh-jadav 

Thanks for looking into this.

Sorry for not specifying this in my initial description.  The screenshots that I posted were based on Advance Card v 2.0.4

Also note that I uploaded the .pbix (renamed to .zip) that contains the custom visual.

![image](https://user-images.githubusercontent.com/3229013/50344040-515d1a00-04f7-11e9-8650-0d10f44867de.png)

**Comment by scrampy** [comment]
Hi - just wondering if there is anything I can do to help you test a potential fix.

Thanks!

**Comment by bhavesh-jadav** [comment]
Hi @scrampy 

Thank you for your interest. I have been busy past few weeks but now I have time. I will try to fix most of the issue(including this one) by end of this week and will update here once fix is available. Then you can test it.

**Comment by bhavesh-jadav** [comment]
@scrampy Can you please check this with latest version (v2.1.0)?

**Comment by scrampy** [comment]
Thanks for the update @bhavesh-jadav - the issue still exists.  I deleted the Advance Card visual from my report, re-imported from the marketplace, recreated the card with the same parameters and deployed to the power BI service.  On iOS in the Power BI app, the vertical alignment of the text in the card is NOTICEABLY lower than on Window10/Chrome.

Did you testing after the changes to v2.1.0 show otherwise?

**Comment by scrampy** [comment]
@bhavesh-jadav any update on this issue?  I see that you still have it listed as Under Investigation.
