### ISSUE TITLE
Seperator in formatting

### ISSUE THREAD

**Issue by svenvu** [bhavesh-jadav/Advance-Card#6]
Hi

Thanks again for making this great custom visual! It's absolutely awesome.
Something that I can't seem to fix is the formatting of the seperator which works fine in the standard card but not in the advance card. I live in Belgium so the seperator for thousands is a point and for decimals we have to use a comma:

![seperator](https://user-images.githubusercontent.com/41591565/43096382-33c68e04-8eb9-11e8-959c-d0831c5300a4.PNG)

This is only tested in power bi desktop. I am using advance card:
Version 1.0.7.0 Updated 5/20/2018

Is this something that could be fixed in a future version?

Friendly greets
Sven

**Comment by bhavesh-jadav** [comment]
I will add the culture support in next version. Thank you for your feedback.

**Comment by svenvu** [comment]
Many thanks! I see it will be available in next version.

**Comment by bhavesh-jadav** [comment]
Fixed in v1.0.8

**Comment by Solteq-VRan** [comment]
There's still an issue with separator, for both the Desktop (2.67.5404.981) and PowerBi.com. In Finland we use space as thousands separator and for decimals we use comma. The visual is showing comma for the thousands and dot for decimals:
![Capture_card](https://user-images.githubusercontent.com/49277268/56578613-bbd1b400-65d6-11e9-90f6-1044d570ac4e.PNG)
