### ISSUE TITLE
Display Units - Auto not working for negative numbers

### ISSUE THREAD

**Issue by RicardoMadaleno** [bhavesh-jadav/Advance-Card#9]
Hi,

Even though I have the option "Auto" selected on the display units section for the data label, when the number is a negative one, it won't abbreviate the number for thousands, millions, etc... It works fine for positive numbers.

I'm using PowerBI Desktop July Update on a windows 10 computer and iPhone 6 with ios 11.

Thanks

**Comment by bhavesh-jadav** [comment]
Hi,

In v1.0.8 which will be available soon (waiting for approval by Microsoft), Auto formatting works with negative number. Meanwhile you can manually select formatting for negative numbers until v1.0.8 is available.
Thank you for your feedback

**Comment by RicardoMadaleno** [comment]
Thank you so much for the quick response. I'll be on the lookout for the new version then :) thanks

**Comment by bhavesh-jadav** [comment]
Fixed in v1.0.8

**Comment by RicardoMadaleno** [comment]
Hi,
Has a new version come out? the marketplace still shows the version 1.0.8.0 released on the 30th of July
(2 days before i posted the issue)

Thanks

**Comment by bhavesh-jadav** [comment]
This issue is fixed in v1.0.8

**Comment by RicardoMadaleno** [comment]
Hi,
I've just tried to update the visual, deleted it and added it again, even used the 1.1.0 version... all with the same results... the auto formatting is still not working with negative numbers
![auto](https://user-images.githubusercontent.com/37866373/44209682-1bc8ae80-a15c-11e8-8be5-16ff2fe1e0bf.PNG)
![manual](https://user-images.githubusercontent.com/37866373/44209683-1bc8ae80-a15c-11e8-837d-38005692176f.PNG)

Am I doing something wrong?
tks

**Comment by bhavesh-jadav** [comment]
I tried on my machine with v1.0.8 and it works. See below gif.
![N|Solid](https://i.imgur.com/UZQF3BN.gif)
Try clearing cache and also make sure that the data type of field is number. Also make sure that you are using v1.0.8 by checking About section.

**Comment by RicardoMadaleno** [comment]
Hi,
You were, of course, right. 
When I checked the About section it was still showing the 1.0.6 version even though I deleted the visual and re-added it... Ended up having to delete it, clear the cache using this method: https://community.powerbi.com/t5/Custom-Visuals-Community-Blog/Power-KPI-1-5-0-cache-issue/ba-p/440189

Thank you for all the help, and I'm sorry for the confusion.

**Comment by bhavesh-jadav** [comment]
Glad it worked out for you :)
